"""create task_list table

Revision ID: 4ecfa840d983
Revises: e88636d96de0
Create Date: 2025-07-09 19:11:02.554026

"""

# revision identifiers, used by Alembic.
revision = "4ecfa840d983"
down_revision = "e88636d96de0"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_list",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_list")
    # ### end Alembic commands ###
